// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiQm9bcblN_XnynkDQ45xbf8yaacYAUa8',
    appId: '1:416231278978:web:1b9314ba8599cc7ce1e79b',
    messagingSenderId: '416231278978',
    projectId: 'chat-c2e7f',
    authDomain: 'chat-c2e7f.firebaseapp.com',
    storageBucket: 'chat-c2e7f.firebasestorage.app',
    measurementId: 'G-1PTQDGDQ0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCclOjV_FdvQ1VPc-tGCji0KgF4H2Rmkcs',
    appId: '1:416231278978:android:67c2113a0d3cd60be1e79b',
    messagingSenderId: '416231278978',
    projectId: 'chat-c2e7f',
    storageBucket: 'chat-c2e7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj1y1QPr5UMS8j9bwdTQKvB0VejgOi3oU',
    appId: '1:416231278978:ios:eae5859d0ab33e02e1e79b',
    messagingSenderId: '416231278978',
    projectId: 'chat-c2e7f',
    storageBucket: 'chat-c2e7f.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj1y1QPr5UMS8j9bwdTQKvB0VejgOi3oU',
    appId: '1:416231278978:ios:eae5859d0ab33e02e1e79b',
    messagingSenderId: '416231278978',
    projectId: 'chat-c2e7f',
    storageBucket: 'chat-c2e7f.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiQm9bcblN_XnynkDQ45xbf8yaacYAUa8',
    appId: '1:416231278978:web:a832a1740f15d2e2e1e79b',
    messagingSenderId: '416231278978',
    projectId: 'chat-c2e7f',
    authDomain: 'chat-c2e7f.firebaseapp.com',
    storageBucket: 'chat-c2e7f.firebasestorage.app',
    measurementId: 'G-F4Q52R9P5D',
  );
}
